### PR TITLE
Automatically retry requests once for non-fatal errors

### LINKED ISSUE #3: Long-running B2 objects eventually throw UNAUTHORIZED on all requests
It appears that B2's auth tokens are time-limited; I'm not sure what the time is, and it's not documented (in an earlier draft of the API docs, it was mentioned that they needed to document when users needed to regenerate auth tokens.)

In my application where a `B2` instance exists for days at a time, the current implementation eventually returns the `UNAUTHORIZED` error on every single request, making the `B2` object unusable until it is recreated (though likely just calling `AuthorizeAccount` on it again would fix it.)

I think the solution that would be really nice is something similar to [what `(*github.com/ncw/swift.Connection).Call()` does](https://github.com/ncw/swift/blob/master/swift.go#L432) - before each request, make sure we're authenticated. If we don't have an auth token, we authenticate (and fail the overall operation if that fails). If we get a 401 during a non-authentication operation, we clear our (now known bad) auth token and retry (and thus reauthenticate.) That's worked well in practice for the companies I've used it at before. (Though note that [the current implementation in ncw/swift is a little wonky](https://github.com/ncw/swift/issues/53).)

I was going to draft a pull request for this, but it requires some pretty serious refactors and a few (fully backwards-compatible) API changes (specifically that `AuthorizeAccount` would no longer be a required call; effectively turning the `B2` object stateless, which is nice on its own sake.)

If you don't think you have the time to do this, I can try my hand at it during my free time.

### PR DESCRIPTION
**Pull request by kothar**
Currently the only non-fatal error is a 401 Unauthorized response, which
will attempt to re-authorize the client to account for expired auth tokens.

Any other non-success (status 200 OK) response will immediately return an
error.

This should close #3

### CODE REVIEW

**Comment by encryptio** [comment]
Looks like there are several race conditions in this code wrt concurrent requests on the B2 object and authorization tokens; the simplest being starting two requests on a newly allocated object (`&B2{...}`, not `NewB2`), a more complicated one being all requests during a token expiry resetting the auth token and causing a new reauth (even if it was already reauthed and set properly before from a concurrent request that ended earlier.)

This kind of thing is what I was afraid of; now that you're doing writes to the B2 object, there's a ton of extra complexity that needs to be added for being safe for concurrent access.

I'm throwing around a few ideas in code, and if any of them work out, I'll link the commits here.

**Comment by kothar** [comment]
The simplest thing to do would be to add a Mutex to the B2 object, and lock the relevant calls. Long-running concurrent tasks such as upload and download would operate on Reader and Writer objects outside the mutual exclusion.

If the Mutex becomes a bottleneck, it should be possible to use a pool of B2 objects to make concurrent requests, although some of the bucket-related methods on B2 might need to be made public to avoid holding references in Bucket objects.

**Comment by encryptio** [comment]
Yeah, but you still have (memory-safe) racy behavior wrt token expiration unless you're really, really careful to only expire the token you used to create the request, not one that's been written since due to a reauth caused by a concurrent request. It might be worth it to just pull out the authorization state to a new object, that way all this subtle code is separated from HTTP API logic.

**Comment by kothar** [comment]
I mean isolate the whole API request with a mutex - eliminate concurrent access to the shared state. It's not going to have good performance with concurrent requests, as it will serialize them, but it will at least put us in a safe starting position from which to work, and concurrent tasks can use their own copy of the client to avoid lock contention if it's a performance problem.

I see what you mean about the auth state in a separate object, that way when replacing the auth token on re-auth, any existing calls won't hold pointers to the new auth state, and can safely mark their (old) copy as invalid. I think so long as there is a lock during the re-auth step to avoid multiple re-auth calls, that could work extremely well.

I won't have much more time to work on this for a couple of days, so I'd be happy to receive any PRs. I will pick this up again at the weekend.

**Comment by kothar** [comment]
@encryptio, I've added mutexes around the modifiable state, and encapsulated the auth state so that it can be independently invalidated. Does this cover what you needed now? The mutex should only be held during authorization (to prevent double auth) and when getting a pointer to the current auth state so that a request can be made.

The same approach is taken with the Bucket upload URL auth state.

**Comment by encryptio** [comment]
Just got a chance to look at this; nothing pops out, looks good!

I'll run it through my code and see if anything breaks, but I suspect this will work great as-is.

**Pull request merged**
