### PR TITLE
Add configurable maxIdleUploads

### PR DESCRIPTION
**Pull request by antihax**
Add configurable maxIdleUploads so users can select risk level of keeping them lingering.

### CODE REVIEW

**Comment by antihax** [comment]
Let me know if this looks like a good method of handling this.

**Comment by kothar** [comment]
Hi, sorry for the slow reply. Yes, I think that looks good.

I would reduce the default to 1 idle upload URL, since that is the least likely to introduce unexpected behaviour for existing users - if the cached URL fails, it will be retried once which will create a new URL and (ideally) succeed.
With 10 cached connections you could see 10 failures before it actually tries with a new URL, which may be more retries than most clients are expecting to deal with.

I would also expect 1 cached URL to be enough for sequential uploads, or for a worker pool uploading a batch of files back-to-back. Multiple cached URLs would be most useful when batches of files will be uploaded in bursts, then return the URLs to the pool until the next burst. Does that fit with your experience using it?

Mike.

**Comment by antihax** [comment]
1 would be sufficient for sequential uploads. I was uploading ~100 at a time per instance with MaxIdleUploads at 100.

I did see a significant decrease in upload_url requests in the statistics.

**Comment by kothar** [comment]
Thanks again for contributing your fix - very much appreciated :)

**Pull request merged**
