### PR TITLE
add concurrent queue for reusing UploadAuth

### PR DESCRIPTION
**Pull request by antihax**
This was the simplest implementation i could think of. 

It will keep a queue of 100 idle upload urls and create a new one only if one is not present on the queue. If one fails, it should not be added back to the queue.

I am not completely sure about the implementation of the return, but since UploadAuth is exported, it made sense to export return also.

Let me know what you think and modify as you see fit.

### CODE REVIEW

**Comment by kothar** [comment]
That looks excellent. I was considering use of sync.Pool, but various blogs seem to suggest a chan buffer as you have implemented unless you are mainly aiming to reduce allocation/garbage collection. I'm happy to merge as-is.

Thanks very much!

**Comment by antihax** [comment]
I tried sync.Pool, it frees the collection each GC cycle apparently.

If you feel it is good enough to merge I think we can go ahead. Just
wondering if there needs to be an expulsion of the queue if the with
invalidates over time. It will handle it, but could cause upto 100 errors
in the process.

**Comment by kothar** [comment]
Hmm, good point. I see a few of options:
1) Shorten the queue (1 entry?), assuming that we only need to keep hold of the authorisation long enough to pass to the next call
2) Expire the auth after a set period of time, reading from the queue until a valid token is found or the end reached
3) Automatically retry if the token was a reused one. The return method could mark the token. It still feels a bit racy if one goroutine was pooling invalid credentials and another trying to use them.

Do you have any preference in approach?

**Comment by antihax** [comment]
let me look at shortening, could drop to 10 or so or make it configurable?
maxIdleUploads.

**Comment by antihax** [comment]
I think the configurable option may be better, I have something I tested last night and looks to work ok. 
That way if the user is just serializing requests, they can set it to one so the it checks in and out each time, or they can set 100+ if they have many concurrent workers.

A user could also manually drain the pool if needed if there will be significant time between usage.

**Pull request merged**
